services:
  django:
    build: .
    container_name: Hangover_container
    ports:
      - "8000:8000"
    depends_on:
      - celery
      - db
    environment:
      - DJANGO__DD_HOST=${DJANGO__DD_HOST}
      - DJANGO__ENVIRONMENT_STATUS=${DJANGO__ENVIRONMENT_STATUS}
    volumes:
      - ./db:/wd/db
    profiles:
      - prod

  celery:
    build:
      context: .
    container_name: celery_worker_container
    command: celery -A BaseApp worker --loglevel=info
    depends_on:
      - redis
    environment:
      - DJANGO__DD_HOST=${DJANGO__DD_HOST}
      - DJANGO__ENVIRONMENT_STATUS=${DJANGO__ENVIRONMENT_STATUS}
    profiles:
      - dev
      - prod

  redis:
    image: redis:latest
    container_name: redis_for_celery_container
    ports:
      - "6400:6379"
    profiles:
      - dev
      - prod

  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    profiles:
      - dev
      - prod






